%PDF-1.4
%Çì¢
5 0 obj
<</Length 6 0 R/Filter /FlateDecode>>
stream
xœm1oƒ0„wÿŠ“:¨Lmx¬Ô¥j†V–:D,‡T§Š²ô·×€ÉPÕ–l=ßù;½w‹9Ø¸ı­y|/PYÂP‘á“iƒ'éëñAÈü‡#ËP¤,NÓÒ]°U_å¡nÊ®2ÆyüÆV]Á
°\¬rÁÖHÏ¼ÌÃOùâ¨OM2P´rïp\„4wFÕ4½e“ŸsÈW$"¼'2Ú©79]À¨º;LÆQ\y~U‹‡v#´±ÓĞjPı±Öv©/u»ï.Ke¯ö\š‰dKpîÙ3Ïgë¾¿…ÿ„S}ó~¸ÆÜYC7€ªÖÖ }¹Wí¹ÖsØz	Ûx–nJÕŠI¤¹÷“b²ƒ(;Œ~İÍ#y–äÍí_^¦}«endstream
endobj
6 0 obj
299
endobj
4 0 obj
<</Type/Page/MediaBox [0 0 612 792]
/Rotate 0/Parent 3 0 R
/Resources<</ProcSet[/PDF /Text]
/ExtGState 10 0 R
/Font 11 0 R
>>
/Contents 5 0 R
>>
endobj
3 0 obj
<< /Type /Pages /Kids [
4 0 R
] /Count 1
>>
endobj
1 0 obj
<</Type /Catalog /Pages 3 0 R
/Metadata 13 0 R
>>
endobj
7 0 obj
<</Type/ExtGState
/OPM 1>>endobj
10 0 obj
<</R7
7 0 R>>
endobj
11 0 obj
<</R9
9 0 R/R8
8 0 R>>
endobj
9 0 obj
<</BaseFont/Courier/Type/Font
/Encoding 12 0 R/Subtype/Type1>>
endobj
12 0 obj
<</Type/Encoding/Differences[
126/tilde]>>
endobj
8 0 obj
<</BaseFont/Courier-Bold/Type/Font
/Subtype/Type1>>
endobj
13 0 obj
<</Type/Metadata
/Subtype/XML/Length 1354>>stream
<?xpacket begin='ï»¿' id='W5M0MpCehiHzreSzNTczkc9d'?>
<?adobe-xap-filters esc="CRLF"?>
<x:xmpmeta xmlns:x='adobe:ns:meta/' x:xmptk='XMP toolkit 2.9.1-13, framework 1.6'>
<rdf:RDF xmlns:rdf='http://www.w3.org/1999/02/22-rdf-syntax-ns#' xmlns:iX='http://ns.adobe.com/iX/1.0/'>
<rdf:Description rdf:about='uuid:c17c9995-2cd5-11f0-0000-d8ddf9fcb7c0' xmlns:pdf='http://ns.adobe.com/pdf/1.3/' pdf:Producer='GPL Ghostscript 9.10'/>
<rdf:Description rdf:about='uuid:c17c9995-2cd5-11f0-0000-d8ddf9fcb7c0' xmlns:xmp='http://ns.adobe.com/xap/1.0/'><xmp:ModifyDate>2015-05-07T09:01:42-04:00</xmp:ModifyDate>
<xmp:CreateDate>2015-05-07T09:01:42-04:00</xmp:CreateDate>
<xmp:CreatorTool>GNU Enscript 1.6.5.90</xmp:CreatorTool></rdf:Description>
<rdf:Description rdf:about='uuid:c17c9995-2cd5-11f0-0000-d8ddf9fcb7c0' xmlns:xapMM='http://ns.adobe.com/xap/1.0/mm/' xapMM:DocumentID='uuid:c17c9995-2cd5-11f0-0000-d8ddf9fcb7c0'/>
<rdf:Description rdf:about='uuid:c17c9995-2cd5-11f0-0000-d8ddf9fcb7c0' xmlns:dc='http://purl.org/dc/elements/1.1/' dc:format='application/pdf'><dc:title><rdf:Alt><rdf:li xml:lang='x-default'>Enscript Output</rdf:li></rdf:Alt></dc:title></rdf:Description>
</rdf:RDF>
</x:xmpmeta>
                                                                        
                                                                        
<?xpacket end='w'?>
endstream
endobj
2 0 obj
<</Producer(GPL Ghostscript 9.10)
/CreationDate(D:20150507090142-04'00')
/ModDate(D:20150507090142-04'00')
/Title(Enscript Output)
/Creator(GNU Enscript 1.6.5.90)>>endobj
xref
0 14
0000000000 65535 f 
0000000622 00000 n 
0000002432 00000 n 
0000000563 00000 n 
0000000403 00000 n 
0000000015 00000 n 
0000000384 00000 n 
0000000687 00000 n 
0000000934 00000 n 
0000000797 00000 n 
0000000728 00000 n 
0000000758 00000 n 
0000000875 00000 n 
0000001001 00000 n 
trailer
<< /Size 14 /Root 1 0 R /Info 2 0 R
/ID [<EAECE1691C4ED55E2B1AA8EFFB661363><EAECE1691C4ED55E2B1AA8EFFB661363>]
>>
startxref
2611
%%EOF
