%PDF-1.4
%«Ïè¢
5 0 obj
<</Length 6 0 R/Filter /FlateDecode>>
stream
xúïíQOÉ0Öﬂ˚+Óõ0S‰¬Äç7Måâqö&>,fA÷1PVò˙‰oó≤J‚iBìﬁ{Nœw”=ÿÇ≠ñﬁ„ú\=êTƒÜÑÏ	∂E–[ú√kfÍÄm»QÉ‡y∏∂Â∫.∞ú,çE¥„õ4„&ùz∂m∞ÌÆK	Ë·‘=«FOó—|a˜çÎ\ª:PÙïõl›ÿahRøiå≤,∆?Î;^p’B∂JD`ƒpBÛÇ∞…“pu{Øs ¥,"πÔ±Êô%Z#%ûj1Ë/πº<Ø*˙@≥W!™zu(“zUÛ™nÕiãÖä»XmdîÛ!w@ìΩëìö™≈„∞ƒê$.À^¢mYv4¡çGËs3‹Êœ•TQQ•@Kæéä:ç˚Døh‚9¢YG4◊qz{Èˇ¢°˛è_ÛÏq¨°œ?†j~ºÁ]Ï®ì*bGÖéég<*¬n¯Ëb &÷µLæZ¡-#èÕ˙öendstream
endobj
6 0 obj
374
endobj
4 0 obj
<</Type/Page/MediaBox [0 0 612 792]
/Rotate 0/Parent 3 0 R
/Resources<</ProcSet[/PDF /Text]
/ExtGState 10 0 R
/Font 11 0 R
>>
/Contents 5 0 R
>>
endobj
3 0 obj
<< /Type /Pages /Kids [
4 0 R
] /Count 1
>>
endobj
1 0 obj
<</Type /Catalog /Pages 3 0 R
/Metadata 13 0 R
>>
endobj
7 0 obj
<</Type/ExtGState
/OPM 1>>endobj
10 0 obj
<</R7
7 0 R>>
endobj
11 0 obj
<</R9
9 0 R/R8
8 0 R>>
endobj
9 0 obj
<</BaseFont/Courier/Type/Font
/Encoding 12 0 R/Subtype/Type1>>
endobj
12 0 obj
<</Type/Encoding/Differences[
126/tilde]>>
endobj
8 0 obj
<</BaseFont/Courier-Bold/Type/Font
/Subtype/Type1>>
endobj
13 0 obj
<</Type/Metadata
/Subtype/XML/Length 1354>>stream
<?xpacket begin='Ôªø' id='W5M0MpCehiHzreSzNTczkc9d'?>
<?adobe-xap-filters esc="CRLF"?>
<x:xmpmeta xmlns:x='adobe:ns:meta/' x:xmptk='XMP toolkit 2.9.1-13, framework 1.6'>
<rdf:RDF xmlns:rdf='http://www.w3.org/1999/02/22-rdf-syntax-ns#' xmlns:iX='http://ns.adobe.com/iX/1.0/'>
<rdf:Description rdf:about='uuid:91c694d8-2cc7-11f0-0000-7e54be1ac8b0' xmlns:pdf='http://ns.adobe.com/pdf/1.3/' pdf:Producer='GPL Ghostscript 9.10'/>
<rdf:Description rdf:about='uuid:91c694d8-2cc7-11f0-0000-7e54be1ac8b0' xmlns:xmp='http://ns.adobe.com/xap/1.0/'><xmp:ModifyDate>2015-05-07T07:20:09-04:00</xmp:ModifyDate>
<xmp:CreateDate>2015-05-07T07:20:09-04:00</xmp:CreateDate>
<xmp:CreatorTool>GNU Enscript 1.6.5.90</xmp:CreatorTool></rdf:Description>
<rdf:Description rdf:about='uuid:91c694d8-2cc7-11f0-0000-7e54be1ac8b0' xmlns:xapMM='http://ns.adobe.com/xap/1.0/mm/' xapMM:DocumentID='uuid:91c694d8-2cc7-11f0-0000-7e54be1ac8b0'/>
<rdf:Description rdf:about='uuid:91c694d8-2cc7-11f0-0000-7e54be1ac8b0' xmlns:dc='http://purl.org/dc/elements/1.1/' dc:format='application/pdf'><dc:title><rdf:Alt><rdf:li xml:lang='x-default'>Enscript Output</rdf:li></rdf:Alt></dc:title></rdf:Description>
</rdf:RDF>
</x:xmpmeta>
                                                                        
                                                                        
<?xpacket end='w'?>
endstream
endobj
2 0 obj
<</Producer(GPL Ghostscript 9.10)
/CreationDate(D:20150507072009-04'00')
/ModDate(D:20150507072009-04'00')
/Title(Enscript Output)
/Creator(GNU Enscript 1.6.5.90)>>endobj
xref
0 14
0000000000 65535 f 
0000000697 00000 n 
0000002507 00000 n 
0000000638 00000 n 
0000000478 00000 n 
0000000015 00000 n 
0000000459 00000 n 
0000000762 00000 n 
0000001009 00000 n 
0000000872 00000 n 
0000000803 00000 n 
0000000833 00000 n 
0000000950 00000 n 
0000001076 00000 n 
trailer
<< /Size 14 /Root 1 0 R /Info 2 0 R
/ID [<C6B363A5A4057C9B1859AA3DBD5350B5><C6B363A5A4057C9B1859AA3DBD5350B5>]
>>
startxref
2686
%%EOF
