%PDF-1.4
%Çì¢
5 0 obj
<</Length 6 0 R/Filter /FlateDecode>>
stream
xœ¥1oƒ0…wÿŠ·™ú @â±J–ªZYêPu°!¨H‡,ıí5Ô$U”©õIgË÷üüé ‚èËí™a÷/)Š	ìÀhÂm™Áƒ²‚y¡¶ìç!‘F"ˆ¢Ê°7o­?òmYå>ŸÅBxj÷‰µ>A¤‰œ%R,
Šİ˜üwõh]Î5ŒÁ)éİB¨µ#éóÄ
uUI¬–ôDPOÌ¥ÇÔäÍ‹œhµ”0º¬ƒ:hi?¹1Ü*¦Ó_2ğ¦7æ¯öÛó¶mZp]w%ø>ßèúXfàU·5ïNİ17àÅàíÅ#@r‡í÷Ö}gû™#½ÁÁ³‹œ¢˜‹1«B_ğÄFK.UqEÿ‡ƒh¡ĞÙgU®kyI€¢«[ƒI0ä?ù²§"ÛÚ•bÏ¶¾†©Ìendstream
endobj
6 0 obj
318
endobj
4 0 obj
<</Type/Page/MediaBox [0 0 612 792]
/Rotate 0/Parent 3 0 R
/Resources<</ProcSet[/PDF /Text]
/ExtGState 10 0 R
/Font 11 0 R
>>
/Contents 5 0 R
>>
endobj
3 0 obj
<< /Type /Pages /Kids [
4 0 R
] /Count 1
>>
endobj
1 0 obj
<</Type /Catalog /Pages 3 0 R
/Metadata 13 0 R
>>
endobj
7 0 obj
<</Type/ExtGState
/OPM 1>>endobj
10 0 obj
<</R7
7 0 R>>
endobj
11 0 obj
<</R9
9 0 R/R8
8 0 R>>
endobj
9 0 obj
<</BaseFont/Courier/Type/Font
/Encoding 12 0 R/Subtype/Type1>>
endobj
12 0 obj
<</Type/Encoding/Differences[
126/tilde]>>
endobj
8 0 obj
<</BaseFont/Courier-Bold/Type/Font
/Subtype/Type1>>
endobj
13 0 obj
<</Type/Metadata
/Subtype/XML/Length 1354>>stream
<?xpacket begin='ï»¿' id='W5M0MpCehiHzreSzNTczkc9d'?>
<?adobe-xap-filters esc="CRLF"?>
<x:xmpmeta xmlns:x='adobe:ns:meta/' x:xmptk='XMP toolkit 2.9.1-13, framework 1.6'>
<rdf:RDF xmlns:rdf='http://www.w3.org/1999/02/22-rdf-syntax-ns#' xmlns:iX='http://ns.adobe.com/iX/1.0/'>
<rdf:Description rdf:about='uuid:161a1762-2cca-11f0-0000-e8e0a8a13cfa' xmlns:pdf='http://ns.adobe.com/pdf/1.3/' pdf:Producer='GPL Ghostscript 9.10'/>
<rdf:Description rdf:about='uuid:161a1762-2cca-11f0-0000-e8e0a8a13cfa' xmlns:xmp='http://ns.adobe.com/xap/1.0/'><xmp:ModifyDate>2015-05-07T07:38:10-04:00</xmp:ModifyDate>
<xmp:CreateDate>2015-05-07T07:38:10-04:00</xmp:CreateDate>
<xmp:CreatorTool>GNU Enscript 1.6.5.90</xmp:CreatorTool></rdf:Description>
<rdf:Description rdf:about='uuid:161a1762-2cca-11f0-0000-e8e0a8a13cfa' xmlns:xapMM='http://ns.adobe.com/xap/1.0/mm/' xapMM:DocumentID='uuid:161a1762-2cca-11f0-0000-e8e0a8a13cfa'/>
<rdf:Description rdf:about='uuid:161a1762-2cca-11f0-0000-e8e0a8a13cfa' xmlns:dc='http://purl.org/dc/elements/1.1/' dc:format='application/pdf'><dc:title><rdf:Alt><rdf:li xml:lang='x-default'>Enscript Output</rdf:li></rdf:Alt></dc:title></rdf:Description>
</rdf:RDF>
</x:xmpmeta>
                                                                        
                                                                        
<?xpacket end='w'?>
endstream
endobj
2 0 obj
<</Producer(GPL Ghostscript 9.10)
/CreationDate(D:20150507073810-04'00')
/ModDate(D:20150507073810-04'00')
/Title(Enscript Output)
/Creator(GNU Enscript 1.6.5.90)>>endobj
xref
0 14
0000000000 65535 f 
0000000641 00000 n 
0000002451 00000 n 
0000000582 00000 n 
0000000422 00000 n 
0000000015 00000 n 
0000000403 00000 n 
0000000706 00000 n 
0000000953 00000 n 
0000000816 00000 n 
0000000747 00000 n 
0000000777 00000 n 
0000000894 00000 n 
0000001020 00000 n 
trailer
<< /Size 14 /Root 1 0 R /Info 2 0 R
/ID [<5D2E76F4A347051CECAF4058E74C527A><5D2E76F4A347051CECAF4058E74C527A>]
>>
startxref
2630
%%EOF
