%PDF-1.4
%Çì¢
5 0 obj
<</Length 6 0 R/Filter /FlateDecode>>
stream
xœmQ=oƒ0Üı+ŞV 2µùÇJíP©M½EC€bREYúÛkƒIH{ğÇ»»wgï€¸ˆfz\ÆPtˆ@vˆöE0‹hà‰+@¢/ø
a±O\ß÷7he¥Ùw¾©êÜÆAHˆÅËH³HÄ‚ˆ‘<BCS¦ö'Uªs£ê…€i¤Õ<àk%G™#ÌêšÁ[)2ÍŠJ@Ï£øY³wV–oÀÜ”ãJX¼|,]Ùs5>0x0£˜ÍîáËik\w›¦ÆÅ>kËJtãùXm×ò8Ã}ª#X¦ÜºCŞ€Í¿Ğ¤2}¡½D7Ş]yå^´íà§T›s„øN,şóz¸•Œï47¤!doõq4úTÿ@î7©gCtü1QçÙ–Á¾Ç½z?ç·?sô®æÛñ¦}endstream
endobj
6 0 obj
318
endobj
4 0 obj
<</Type/Page/MediaBox [0 0 612 792]
/Rotate 0/Parent 3 0 R
/Resources<</ProcSet[/PDF /Text]
/ExtGState 10 0 R
/Font 11 0 R
>>
/Contents 5 0 R
>>
endobj
3 0 obj
<< /Type /Pages /Kids [
4 0 R
] /Count 1
>>
endobj
1 0 obj
<</Type /Catalog /Pages 3 0 R
/Metadata 13 0 R
>>
endobj
7 0 obj
<</Type/ExtGState
/OPM 1>>endobj
10 0 obj
<</R7
7 0 R>>
endobj
11 0 obj
<</R9
9 0 R/R8
8 0 R>>
endobj
9 0 obj
<</BaseFont/Courier/Type/Font
/Encoding 12 0 R/Subtype/Type1>>
endobj
12 0 obj
<</Type/Encoding/Differences[
126/tilde]>>
endobj
8 0 obj
<</BaseFont/Courier-Bold/Type/Font
/Subtype/Type1>>
endobj
13 0 obj
<</Type/Metadata
/Subtype/XML/Length 1354>>stream
<?xpacket begin='ï»¿' id='W5M0MpCehiHzreSzNTczkc9d'?>
<?adobe-xap-filters esc="CRLF"?>
<x:xmpmeta xmlns:x='adobe:ns:meta/' x:xmptk='XMP toolkit 2.9.1-13, framework 1.6'>
<rdf:RDF xmlns:rdf='http://www.w3.org/1999/02/22-rdf-syntax-ns#' xmlns:iX='http://ns.adobe.com/iX/1.0/'>
<rdf:Description rdf:about='uuid:99d7027e-2cd0-11f0-0000-4a7d4ec15050' xmlns:pdf='http://ns.adobe.com/pdf/1.3/' pdf:Producer='GPL Ghostscript 9.10'/>
<rdf:Description rdf:about='uuid:99d7027e-2cd0-11f0-0000-4a7d4ec15050' xmlns:xmp='http://ns.adobe.com/xap/1.0/'><xmp:ModifyDate>2015-05-07T08:24:48-04:00</xmp:ModifyDate>
<xmp:CreateDate>2015-05-07T08:24:48-04:00</xmp:CreateDate>
<xmp:CreatorTool>GNU Enscript 1.6.5.90</xmp:CreatorTool></rdf:Description>
<rdf:Description rdf:about='uuid:99d7027e-2cd0-11f0-0000-4a7d4ec15050' xmlns:xapMM='http://ns.adobe.com/xap/1.0/mm/' xapMM:DocumentID='uuid:99d7027e-2cd0-11f0-0000-4a7d4ec15050'/>
<rdf:Description rdf:about='uuid:99d7027e-2cd0-11f0-0000-4a7d4ec15050' xmlns:dc='http://purl.org/dc/elements/1.1/' dc:format='application/pdf'><dc:title><rdf:Alt><rdf:li xml:lang='x-default'>Enscript Output</rdf:li></rdf:Alt></dc:title></rdf:Description>
</rdf:RDF>
</x:xmpmeta>
                                                                        
                                                                        
<?xpacket end='w'?>
endstream
endobj
2 0 obj
<</Producer(GPL Ghostscript 9.10)
/CreationDate(D:20150507082448-04'00')
/ModDate(D:20150507082448-04'00')
/Title(Enscript Output)
/Creator(GNU Enscript 1.6.5.90)>>endobj
xref
0 14
0000000000 65535 f 
0000000641 00000 n 
0000002451 00000 n 
0000000582 00000 n 
0000000422 00000 n 
0000000015 00000 n 
0000000403 00000 n 
0000000706 00000 n 
0000000953 00000 n 
0000000816 00000 n 
0000000747 00000 n 
0000000777 00000 n 
0000000894 00000 n 
0000001020 00000 n 
trailer
<< /Size 14 /Root 1 0 R /Info 2 0 R
/ID [<B93144F27E745329DD4D84F88829DA96><B93144F27E745329DD4D84F88829DA96>]
>>
startxref
2630
%%EOF
