%PDF-1.4
%«Ïè¢
5 0 obj
<</Length 6 0 R/Filter /FlateDecode>>
stream
xúïëΩn¬0Öw?≈›öP9µ¿#Ró™Eñ:†
π¡ISÚGTuÈ≥◊6&çç•X∫>˜¯;◊ bñ€ì=¨gêuà@Üà⁄Cp[R¬Rh¡‹DäN=ÉYDÇ(ä@îh„≠‰^•y°|<eÑx‚®`%øÅ0†s.8õBH(s«‘O⁄u·\Cò∆∆-±”vî˚8÷BYöéI€@)àg‰Ö‹øCb≤Ò"ß2ΩÍ˙†Üu^eÀcö™6®móQNù‹ó›ﬂ_”ÆÌmÄã˜∫Ó˙Ì± ˚≠n”VñÍ´n˜÷”cgÜxƒ‘é"iö±ÔG”$≥+$8˘k√Ø:≥˛´∂≠[¿≤Ír¿ç⁄…™œì\÷€!R3?œÇŒ|ÒâFÂ97C±p„|å|#éœf˙ç»ı(.ˇt∫Ö.Ê—‰]†—!•C":ö§P≤‚√ºitA	m	ì¿ΩÛ‰«
z—ÎﬂÚ◊endstream
endobj
6 0 obj
365
endobj
4 0 obj
<</Type/Page/MediaBox [0 0 612 792]
/Rotate 0/Parent 3 0 R
/Resources<</ProcSet[/PDF /Text]
/ExtGState 10 0 R
/Font 11 0 R
>>
/Contents 5 0 R
>>
endobj
3 0 obj
<< /Type /Pages /Kids [
4 0 R
] /Count 1
>>
endobj
1 0 obj
<</Type /Catalog /Pages 3 0 R
/Metadata 13 0 R
>>
endobj
7 0 obj
<</Type/ExtGState
/OPM 1>>endobj
10 0 obj
<</R7
7 0 R>>
endobj
11 0 obj
<</R9
9 0 R/R8
8 0 R>>
endobj
9 0 obj
<</BaseFont/Courier/Type/Font
/Encoding 12 0 R/Subtype/Type1>>
endobj
12 0 obj
<</Type/Encoding/Differences[
126/tilde]>>
endobj
8 0 obj
<</BaseFont/Courier-Bold/Type/Font
/Subtype/Type1>>
endobj
13 0 obj
<</Type/Metadata
/Subtype/XML/Length 1354>>stream
<?xpacket begin='Ôªø' id='W5M0MpCehiHzreSzNTczkc9d'?>
<?adobe-xap-filters esc="CRLF"?>
<x:xmpmeta xmlns:x='adobe:ns:meta/' x:xmptk='XMP toolkit 2.9.1-13, framework 1.6'>
<rdf:RDF xmlns:rdf='http://www.w3.org/1999/02/22-rdf-syntax-ns#' xmlns:iX='http://ns.adobe.com/iX/1.0/'>
<rdf:Description rdf:about='uuid:e8cc69d9-2cc7-11f0-0000-d1142adfe3b3' xmlns:pdf='http://ns.adobe.com/pdf/1.3/' pdf:Producer='GPL Ghostscript 9.10'/>
<rdf:Description rdf:about='uuid:e8cc69d9-2cc7-11f0-0000-d1142adfe3b3' xmlns:xmp='http://ns.adobe.com/xap/1.0/'><xmp:ModifyDate>2015-05-07T07:22:35-04:00</xmp:ModifyDate>
<xmp:CreateDate>2015-05-07T07:22:35-04:00</xmp:CreateDate>
<xmp:CreatorTool>GNU Enscript 1.6.5.90</xmp:CreatorTool></rdf:Description>
<rdf:Description rdf:about='uuid:e8cc69d9-2cc7-11f0-0000-d1142adfe3b3' xmlns:xapMM='http://ns.adobe.com/xap/1.0/mm/' xapMM:DocumentID='uuid:e8cc69d9-2cc7-11f0-0000-d1142adfe3b3'/>
<rdf:Description rdf:about='uuid:e8cc69d9-2cc7-11f0-0000-d1142adfe3b3' xmlns:dc='http://purl.org/dc/elements/1.1/' dc:format='application/pdf'><dc:title><rdf:Alt><rdf:li xml:lang='x-default'>Enscript Output</rdf:li></rdf:Alt></dc:title></rdf:Description>
</rdf:RDF>
</x:xmpmeta>
                                                                        
                                                                        
<?xpacket end='w'?>
endstream
endobj
2 0 obj
<</Producer(GPL Ghostscript 9.10)
/CreationDate(D:20150507072235-04'00')
/ModDate(D:20150507072235-04'00')
/Title(Enscript Output)
/Creator(GNU Enscript 1.6.5.90)>>endobj
xref
0 14
0000000000 65535 f 
0000000688 00000 n 
0000002498 00000 n 
0000000629 00000 n 
0000000469 00000 n 
0000000015 00000 n 
0000000450 00000 n 
0000000753 00000 n 
0000001000 00000 n 
0000000863 00000 n 
0000000794 00000 n 
0000000824 00000 n 
0000000941 00000 n 
0000001067 00000 n 
trailer
<< /Size 14 /Root 1 0 R /Info 2 0 R
/ID [<6BA00699EAF9A1964708CB293D6C1F6C><6BA00699EAF9A1964708CB293D6C1F6C>]
>>
startxref
2677
%%EOF
